// mock data
export const mockUser = {
    id: '0a423e5a-d34a-11e7-9a41-c2a5d78378ac',
    firstName: '',
    lastName: '',
    username: 'u-bjbd4wwtjii6pgsbyks5pa3yvq',
    emails: [
        {
            value: 'foo@foo.com',
        },
    ],
    provider: 'helsinki',
    _raw: '{"last_login":"2018-01-19T07:33:42.102250Z","username":"u-ajbd4wwtjii6pgsbyks5pa3yvq","email":"foo@foo.com","date_joined":"2017-11-27T08:07:41.123918Z","first_name":"","last_name":"","uuid":"0a423e5a-d34a-11e7-9a41-c2a5d78378ac","department_name":null}',
    _json: {
        last_login: '2018-01-19T07:33:42.102250Z',
        username: 'u-ajbd4wwtjii6pgsbyks5pa3yvq',
        email: 'foo@foo.com',
        date_joined: '2017-11-27T08:07:41.123918Z',
        first_name: '',
        last_name: '',
        uuid: '0a423e5a-d34a-11e7-9a41-c2a5d78378ac',
        department_name: null,
    },
    token: 'sometoken',
    organization: 'ahjo:02100',
    userType: 'admin',
    adminOrganizationData: {
        'ahjo:02100': {
            id: 'ahjoID',
        },
    },
};

export const mockUserEvents = [
    {
        publication_status: 'public',
        created_time: '2018-01-16T12:07:21.701359Z',
        last_modified_time: '2018-01-16T12:07:21.701386Z',
        start_time: '2018-01-31T11:13:00Z',
        end_time: '2018-01-31T12:14:00Z',
        name: {
            fi: 'TestEvent1',
        },
        short_description: {
            fi: 'TestEvent1',
        },
        description: {
            fi: '<p>TestEvent1</p>',
        },
        '@id': 'https://api.hel.fi/linkedevents-test/v1/event/helsinki:afqp5xo7ly/',
    },
    {
        publication_status: 'public',
        created_time: '2018-01-11T13:27:23.840820Z',
        last_modified_time: '2018-01-11T13:27:23.840843Z',
        start_time: '2018-02-02T13:00:00Z',
        end_time: '2018-02-02T14:00:00Z',
        name: {
            fi: 'Pomppu',
        },
        short_description: {
            fi: 'Hypähdys',
        },
        '@id': 'https://api.hel.fi/linkedevents-test/v1/event/helsinki:afqokz2zxm/',
    },
    {
        publication_status: 'draft',
        created_time: '2018-01-11T13:27:23.840820Z',
        last_modified_time: '2018-01-11T13:27:23.840843Z',
        start_time: '2023-02-02T13:00:00Z',
        end_time: '2023-02-02T14:00:00Z',
        name: {
            fi: 'Pomppu',
        },
        short_description: {
            fi: 'Hypähdys',
        },
        '@id': 'https://api.hel.fi/linkedevents-test/v1/event/helsinki:afqokz2zxm/',
    },
];

export const mockSideFields = [
    {
        type_id: 'General',
        sidefieldset_name: 'General',
        category_mobile: {
            fi: 'category_mobile_fi',
            sv: 'category_mobile_sv',
            en: 'category_mobile_en',
        },
        umbrella_mobile: {
            fi: 'umbrella_mobile_fi',
            sv: 'umbrella_mobile_sv',
            en: 'umbrella_mobile_en',
        },
        offers_mobile: {
            fi: 'offers_mobile_fi',
            sv: 'offers_mobile_sv',
            en: 'offers_mobile_en',
        },
        times_mobile: {
            fi: 'times_mobile_fi',
            sv: 'times_mobile_sv',
            en: 'times_mobile_en',
        },
        times_sidefield: {
            fi: 'times_sidefield_fi',
            sv: 'times_sidefield_sv',
            en: 'times_sidefield_en',
        },
        keyword_sidefield: {
            fi: 'keyword_sidefield_fi',
            sv: 'keyword_sidefield_sv',
            en: 'keyword_sidefield_en',
        },
        offers_sidefield: {
            fi: 'offers_sidefield_fi',
            sv: 'offers_sidefield_sv',
            en: 'offers_sidefield_en',
        },
        location_sidefield: {
            fi: 'location_sidefield_fi',
            sv: 'location_sidefield_sv',
            en: 'location_sidefield_en',
        },
        keyword_mobile: {
            fi: 'keyword_mobile_fi',
            sv: 'keyword_mobile_sv',
            en: 'keyword_mobile_en',
        },
        category_sidefield: {
            fi: 'category_sidefield_fi',
            sv: 'category_sidefield_sv',
            en: 'category_sidefield_en',
        },
        umbrella_sidefield: {
            fi: 'umbrella_sidefield_fi',
            sv: 'umbrella_sidefield_sv',
            en: 'umbrella_sidefield_en',
        },
        location_mobile: {
            fi: 'location_mobile_fi',
            sv: 'location_mobile_sv',
            en: 'location_mobile_en',
        },
    },
]


export const mockPaymentMethods = [
    {
        id: '1',
        name: {
            fi: 'testikortit',
            en: 'test cards',
            sv: 'testkort',
        },
        '@id': 'https://api.hel.fi/linkedevents-test/v1/paymentmethod/1/',
        '@context': 'http://schema.org',
        '@type': 'PaymentMethod',
    },
    {
        id: '2',
        name: {
            fi: 'testisetelit',
            en: 'test vouchers',
            sv: 'test sedlar',
        },
        '@id': 'https://api.hel.fi/linkedevents-test/v1/paymentmethod/2/',
        '@context': 'http://schema.org',
        '@type': 'PaymentMethod',
    },
    {
        id: '3',
        name: {
            fi: 'testikolikot',
            en: 'test coins',
            sv: 'testmynt',
        },
        '@id': 'https://api.hel.fi/linkedevents-test/v1/paymentmethod/3/',
        '@context': 'http://schema.org',
        '@type': 'PaymentMethod',
    },
];

export const mockKeywordSets = [
    {
        id: 'helfi:topics',
        keywords: [
            {
                id: 'helfi:11',
                alt_labels: [],
                created_time: '2015-01-13T12:00:00Z',
                last_modified_time: '2015-01-13T12:00:00Z',
                aggregate: false,
                deprecated: false,
                n_events: 63,
                data_source: 'helfi',
                image: null,
                publisher: null,
                name: {
                    en: 'Daycare and education',
                    sv: 'Dagvård och utbildning',
                    fi: 'Päivähoito ja koulutus',
                },
                '@id': 'https://api.hel.fi/linkedevents-test/v1/keyword/helfi:11/',
                '@context': 'http://schema.org',
                '@type': 'Keyword',
            },
            {
                id: 'helfi:13',
                alt_labels: [],
                created_time: '2015-01-13T12:00:00Z',
                last_modified_time: '2015-01-13T12:00:00Z',
                aggregate: false,
                deprecated: false,
                n_events: 139,
                data_source: 'helfi',
                image: null,
                publisher: null,
                name: {
                    en: 'Housing and environment',
                    sv: 'Boende och miljö',
                    fi: 'Asuminen ja ympäristö',
                },
                '@id': 'https://api.hel.fi/linkedevents-test/v1/keyword/helfi:13/',
                '@context': 'http://schema.org',
                '@type': 'Keyword',
            },
            {
                id: 'helfi:12',
                alt_labels: [],
                created_time: '2015-01-13T12:00:00Z',
                last_modified_time: '2015-01-13T12:00:00Z',
                aggregate: false,
                deprecated: false,
                n_events: 496,
                data_source: 'helfi',
                image: null,
                publisher: null,
                name: {
                    en: 'Culture and leisure',
                    sv: 'Kultur och fritid',
                    fi: 'Kulttuuri ja vapaa-aika',
                },
                '@id': 'https://api.hel.fi/linkedevents-test/v1/keyword/helfi:12/',
                '@context': 'http://schema.org',
                '@type': 'Keyword',
            },
            {
                id: 'helfi:8',
                alt_labels: [],
                created_time: '2015-01-13T12:00:00Z',
                last_modified_time: '2015-01-13T12:00:00Z',
                aggregate: false,
                deprecated: false,
                n_events: 43,
                data_source: 'helfi',
                image: null,
                publisher: null,
                name: {
                    en: 'City administration',
                    sv: 'Staden och förvaltning',
                    fi: 'Kaupunki ja hallinto',
                },
                '@id': 'https://api.hel.fi/linkedevents-test/v1/keyword/helfi:8/',
                '@context': 'http://schema.org',
                '@type': 'Keyword',
            },
            {
                id: 'helfi:9',
                alt_labels: [],
                created_time: '2015-01-13T12:00:00Z',
                last_modified_time: '2015-01-13T12:00:00Z',
                aggregate: false,
                deprecated: false,
                n_events: 152,
                data_source: 'helfi',
                image: null,
                publisher: null,
                name: {
                    en: 'Social services and health care',
                    sv: 'Social- och hälsovård',
                    fi: 'Sosiaali- ja terveyspalvelut',
                },
                '@id': 'https://api.hel.fi/linkedevents-test/v1/keyword/helfi:9/',
                '@context': 'http://schema.org',
                '@type': 'Keyword',
            },
            {
                id: 'helfi:10',
                alt_labels: [],
                created_time: '2015-01-13T12:00:00Z',
                last_modified_time: '2015-01-13T12:00:00Z',
                aggregate: false,
                deprecated: false,
                n_events: 151,
                data_source: 'helfi',
                image: null,
                publisher: null,
                name: {
                    en: 'Maps and transport',
                    sv: 'Kartor och trafik',
                    fi: 'Liikenne ja kartat',
                },
                '@id': 'https://api.hel.fi/linkedevents-test/v1/keyword/helfi:10/',
                '@context': 'http://schema.org',
                '@type': 'Keyword',
            },
        ],
        usage: 'keyword',
        created_time: '2015-01-13T12:00:00Z',
        last_modified_time: '2015-01-13T12:00:00Z',
        data_source: 'helfi',
        image: null,
        organization: null,
        name: {
            en: 'www.hel.fi themes',
            sv: 'www.hel.fi-teman',
            fi: 'www.hel.fi-aihepiirit',
        },
        '@id': 'https://api.hel.fi/linkedevents-test/v1/keyword_set/helfi:topics/',
        '@context': 'http://schema.org',
        '@type': 'KeywordSet',
    },
    {
        id: 'helfi:audiences',
        keywords: [
            {
                id: 'helfi:5',
                alt_labels: [],
                created_time: '2015-01-13T12:00:00Z',
                last_modified_time: '2015-01-13T12:00:00Z',
                aggregate: false,
                deprecated: false,
                n_events: 76,
                data_source: 'helfi',
                image: null,
                publisher: null,
                name: {
                    en: 'Elderly',
                    sv: 'Äldre',
                    fi: 'Vanhukset',
                },
                '@id': 'https://api.hel.fi/linkedevents-test/v1/keyword/helfi:5/',
                '@context': 'http://schema.org',
                '@type': 'Keyword',
            },
            {
                id: 'helfi:1',
                alt_labels: [],
                created_time: '2015-01-13T12:00:00Z',
                last_modified_time: '2015-01-13T12:00:00Z',
                aggregate: false,
                deprecated: false,
                n_events: 142,
                data_source: 'helfi',
                image: null,
                publisher: null,
                name: {
                    en: 'Children and families',
                    sv: 'Barn och barnfamiljer',
                    fi: 'Lapset ja lapsiperheet',
                },
                '@id': 'https://api.hel.fi/linkedevents-test/v1/keyword/helfi:1/',
                '@context': 'http://schema.org',
                '@type': 'Keyword',
            },
            {
                id: 'helfi:3',
                alt_labels: [],
                created_time: '2015-01-13T12:00:00Z',
                last_modified_time: '2015-01-13T12:00:00Z',
                aggregate: false,
                deprecated: false,
                n_events: 67,
                data_source: 'helfi',
                image: null,
                publisher: null,
                name: {
                    en: 'Immigrants',
                    sv: 'Invandrare',
                    fi: 'Maahanmuuttajat',
                },
                '@id': 'https://api.hel.fi/linkedevents-test/v1/keyword/helfi:3/',
                '@context': 'http://schema.org',
                '@type': 'Keyword',
            },
            {
                id: 'helfi:7',
                alt_labels: [],
                created_time: '2015-01-13T12:00:00Z',
                last_modified_time: '2015-01-13T12:00:00Z',
                aggregate: false,
                deprecated: false,
                n_events: 9,
                data_source: 'helfi',
                image: null,
                publisher: null,
                name: {
                    en: 'Associations',
                    sv: 'Föreningar',
                    fi: 'Yhdistykset',
                },
                '@id': 'https://api.hel.fi/linkedevents-test/v1/keyword/helfi:7/',
                '@context': 'http://schema.org',
                '@type': 'Keyword',
            },
            {
                id: 'helfi:4',
                alt_labels: [],
                created_time: '2015-01-13T12:00:00Z',
                last_modified_time: '2015-01-13T12:00:00Z',
                aggregate: false,
                deprecated: false,
                n_events: 9,
                data_source: 'helfi',
                image: null,
                publisher: null,
                name: {
                    en: 'Disabled',
                    sv: 'Funktionshindrade',
                    fi: 'Vammaiset',
                },
                '@id': 'https://api.hel.fi/linkedevents-test/v1/keyword/helfi:4/',
                '@context': 'http://schema.org',
                '@type': 'Keyword',
            },
            {
                id: 'helfi:2',
                alt_labels: [],
                created_time: '2015-01-13T12:00:00Z',
                last_modified_time: '2015-01-13T12:00:00Z',
                aggregate: false,
                deprecated: false,
                n_events: 98,
                data_source: 'helfi',
                image: null,
                publisher: null,
                name: {
                    en: 'Youth',
                    sv: 'Unga',
                    fi: 'Nuoret',
                },
                '@id': 'https://api.hel.fi/linkedevents-test/v1/keyword/helfi:2/',
                '@context': 'http://schema.org',
                '@type': 'Keyword',
            },
            {
                id: 'helfi:6',
                alt_labels: [],
                created_time: '2015-01-13T12:00:00Z',
                last_modified_time: '2015-01-13T12:00:00Z',
                aggregate: false,
                deprecated: false,
                n_events: 8,
                data_source: 'helfi',
                image: null,
                publisher: null,
                name: {
                    en: 'Entrepreneurs',
                    sv: 'Företagare',
                    fi: 'Yritykset',
                },
                '@id': 'https://api.hel.fi/linkedevents-test/v1/keyword/helfi:6/',
                '@context': 'http://schema.org',
                '@type': 'Keyword',
            },
        ],
        usage: 'audience',
        created_time: null,
        last_modified_time: null,
        data_source: 'helfi',
        image: null,
        organization: null,
        name: {
            en: 'www.hel.fi resident groups',
            sv: 'www.hel.fi-invånargrupper',
            fi: 'www.hel.fi-kohderyhmät',
        },
        '@id': 'https://api.hel.fi/linkedevents-test/v1/keyword_set/helfi:audiences/',
        '@context': 'http://schema.org',
        '@type': 'KeywordSet',
    },
    {
        id: 'helsinki:audiences',
        keywords: [
            {
                id: 'yso:p7179',
                alt_labels: [
                    'funktionshindrade',
                    'monivammaiset',
                    'multihandikappade',
                    'invalidit',
                    'invalider',
                    'personer med handikapp',
                    'people with disabilities',
                    'personer med funktionshinder',
                ],
                created_time: '2014-06-23T11:37:28.866000Z',
                last_modified_time: '2017-09-05T14:42:43.882641Z',
                aggregate: false,
                deprecated: false,
                n_events: 10,
                data_source: 'yso',
                image: null,
                publisher: 'hy:kansalliskirjasto',
                name: {
                    en: 'disabled people',
                    sv: 'handikappade',
                    fi: 'vammaiset',
                },
                '@id': 'https://api.hel.fi/linkedevents-test/v1/keyword/yso:p7179/',
                '@context': 'http://schema.org',
                '@type': 'Keyword',
            },
            {
                id: 'yso:p4354',
                alt_labels: [
                    'spädbarn',
                    'lapset',
                    'imeväisikäiset',
                    'barn',
                ],
                created_time: '2014-06-23T11:37:27.705000Z',
                last_modified_time: '2017-09-05T14:42:54.041059Z',
                aggregate: false,
                deprecated: false,
                n_events: 18597,
                data_source: 'yso',
                image: null,
                publisher: 'hy:kansalliskirjasto',
                name: {
                    en: 'children (age groups)',
                    sv: 'barn (åldersgrupper)',
                    fi: 'lapset (ikäryhmät)',
                },
                '@id': 'https://api.hel.fi/linkedevents-test/v1/keyword/yso:p4354/',
                '@context': 'http://schema.org',
                '@type': 'Keyword',
            },
            {
                id: 'yso:p13050',
                alt_labels: [],
                created_time: '2014-06-23T11:37:23.969000Z',
                last_modified_time: '2017-09-05T14:42:42.446458Z',
                aggregate: false,
                deprecated: false,
                n_events: 199,
                data_source: 'yso',
                image: null,
                publisher: 'hy:kansalliskirjasto',
                name: {
                    en: 'families with children',
                    sv: 'barnfamiljer',
                    fi: 'lapsiperheet',
                },
                '@id': 'https://api.hel.fi/linkedevents-test/v1/keyword/yso:p13050/',
                '@context': 'http://schema.org',
                '@type': 'Keyword',
            },
            {
                id: 'yso:p6165',
                alt_labels: [
                    'immigranter',
                    'immigrantit',
                ],
                created_time: '2014-06-23T11:37:28.630000Z',
                last_modified_time: '2017-09-05T14:42:31.057402Z',
                aggregate: false,
                deprecated: false,
                n_events: 7494,
                data_source: 'yso',
                image: null,
                publisher: 'hy:kansalliskirjasto',
                name: {
                    en: 'immigrants',
                    sv: 'invandrare',
                    fi: 'maahanmuuttajat',
                },
                '@id': 'https://api.hel.fi/linkedevents-test/v1/keyword/yso:p6165/',
                '@context': 'http://schema.org',
                '@type': 'Keyword',
            },
            {
                id: 'yso:p11617',
                alt_labels: [
                    'tonåringar',
                    'nuoriso',
                    'teini-ikäiset',
                    'unga',
                ],
                created_time: '2014-06-23T11:37:27.563000Z',
                last_modified_time: '2017-09-05T14:43:00.842671Z',
                aggregate: false,
                deprecated: false,
                n_events: 12983,
                data_source: 'yso',
                image: null,
                publisher: 'hy:kansalliskirjasto',
                name: {
                    en: 'young people',
                    sv: 'ungdomar',
                    fi: 'nuoret',
                },
                '@id': 'https://api.hel.fi/linkedevents-test/v1/keyword/yso:p11617/',
                '@context': 'http://schema.org',
                '@type': 'Keyword',
            },
            {
                id: 'yso:p3128',
                alt_labels: [
                    'businesses',
                    'affärsföretag',
                    'liikeyritykset',
                ],
                created_time: '2014-06-23T11:37:24.651000Z',
                last_modified_time: '2017-09-05T14:42:58.508500Z',
                aggregate: false,
                deprecated: false,
                n_events: 8,
                data_source: 'yso',
                image: null,
                publisher: 'hy:kansalliskirjasto',
                name: {
                    en: 'enterprises',
                    sv: 'företag',
                    fi: 'yritykset',
                },
                '@id': 'https://api.hel.fi/linkedevents-test/v1/keyword/yso:p3128/',
                '@context': 'http://schema.org',
                '@type': 'Keyword',
            },
            {
                id: 'yso:p1393',
                alt_labels: [
                    'seurat -- järjestötoiminta',
                    'yhdistykset',
                ],
                created_time: '2014-06-23T11:37:27.364000Z',
                last_modified_time: '2017-09-05T14:42:36.625794Z',
                aggregate: false,
                deprecated: false,
                n_events: 9,
                data_source: 'yso',
                image: null,
                publisher: 'hy:kansalliskirjasto',
                name: {
                    en: 'associations',
                    sv: 'föreningar',
                    fi: 'järjestöt',
                },
                '@id': 'https://api.hel.fi/linkedevents-test/v1/keyword/yso:p1393/',
                '@context': 'http://schema.org',
                '@type': 'Keyword',
            },
            {
                id: 'yso:p2434',
                alt_labels: [
                    'ikäihmiset',
                    'ikä-ihmiset',
                    'gamlingar',
                ],
                created_time: '2014-06-23T11:37:30.235000Z',
                last_modified_time: '2017-09-05T14:43:05.106064Z',
                aggregate: false,
                deprecated: false,
                n_events: 4286,
                data_source: 'yso',
                image: null,
                publisher: 'hy:kansalliskirjasto',
                name: {
                    en: 'elderly',
                    sv: 'åldringar',
                    fi: 'vanhukset',
                },
                '@id': 'https://api.hel.fi/linkedevents-test/v1/keyword/yso:p2434/',
                '@context': 'http://schema.org',
                '@type': 'Keyword',
            },
            {
                id: 'yso:p12297',
                alt_labels: [
                    'mentalvårdsklienter',
                    'klienter inom psykisk rehabilitering',
                    'psykiska rehabiliteringspatienter',
                ],
                created_time: '2014-06-23T11:37:29.472000Z',
                last_modified_time: '2017-09-05T14:43:12.305002Z',
                aggregate: false,
                deprecated: false,
                n_events: 0,
                data_source: 'yso',
                image: null,
                publisher: 'hy:kansalliskirjasto',
                name: {
                    en: 'patients in psychiatric rehabilitation',
                    sv: 'klienter i psykisk rehabilitering',
                    fi: 'mielenterveyskuntoutujat',
                },
                '@id': 'https://api.hel.fi/linkedevents-test/v1/keyword/yso:p12297/',
                '@context': 'http://schema.org',
                '@type': 'Keyword',
            },
            {
                id: 'yso:p23886',
                alt_labels: [
                    'rehabiliterade missbrukare',
                    'klienter i missbrukarvård',
                    'klienter i missbruksvård',
                    'klienter i missbruksrehabilitering',
                    'rehabiliteringspatienter (missbruk)',
                ],
                created_time: '2014-06-23T11:37:30.575000Z',
                last_modified_time: '2017-09-05T14:42:53.995580Z',
                aggregate: false,
                deprecated: false,
                n_events: 8,
                data_source: 'yso',
                image: null,
                publisher: 'hy:kansalliskirjasto',
                name: {
                    en: 'substance abuse rehabilitation patients',
                    sv: 'klienter i missbrukarrehabilitering',
                    fi: 'päihdekuntoutujat',
                },
                '@id': 'https://api.hel.fi/linkedevents-test/v1/keyword/yso:p23886/',
                '@context': 'http://schema.org',
                '@type': 'Keyword',
            },
            {
                id: 'helsinki:aflfbatkwe',
                alt_labels: [],
                created_time: null,
                last_modified_time: '2017-03-17T13:12:38.921627Z',
                aggregate: false,
                deprecated: false,
                n_events: 0,
                data_source: 'helsinki',
                image: null,
                publisher: null,
                name: {
                    fi: 'omaishoitoperheet',
                },
                '@id': 'https://api.hel.fi/linkedevents-test/v1/keyword/helsinki:aflfbatkwe/',
                '@context': 'http://schema.org',
                '@type': 'Keyword',
            },
            {
                id: 'helsinki:aflfbat76e',
                alt_labels: [],
                created_time: null,
                last_modified_time: '2017-03-17T13:12:38.926826Z',
                aggregate: false,
                deprecated: false,
                n_events: 0,
                data_source: 'helsinki',
                image: null,
                publisher: null,
                name: {
                    fi: 'palvelukeskuskortti',
                },
                '@id': 'https://api.hel.fi/linkedevents-test/v1/keyword/helsinki:aflfbat76e/',
                '@context': 'http://schema.org',
                '@type': 'Keyword',
            },
        ],
        usage: 'audience',
        created_time: null,
        last_modified_time: '2017-03-17T13:12:38.934562Z',
        data_source: 'helsinki',
        image: null,
        organization: null,
        name: {
            en: 'Helsinki audiences',
            sv: 'Helsingfors invånargrupper',
            fi: 'Helsinki kohderyhmät',
        },
        '@id': 'https://api.hel.fi/linkedevents-test/v1/keyword_set/helsinki:audiences/',
        '@context': 'http://schema.org',
        '@type': 'KeywordSet',
    },
];

export const mockLanguages = [
    {
        id: 'en',
        translation_available: true,
        name: {
            fi: 'englanti',
        },
        '@id': 'https://api.hel.fi/linkedevents-test/v1/language/en/',
        '@context': 'http://schema.org',
        '@type': 'Language',
    },
    {
        id: 'sv',
        translation_available: true,
        name: {
            fi: 'ruotsi',
        },
        '@id': 'https://api.hel.fi/linkedevents-test/v1/language/sv/',
        '@context': 'http://schema.org',
        '@type': 'Language',
    },
    {
        id: 'fi',
        translation_available: true,
        name: {
            fi: 'suomi',
        },
        '@id': 'https://api.hel.fi/linkedevents-test/v1/language/fi/',
        '@context': 'http://schema.org',
        '@type': 'Language',
    },
    {
        id: 'ru',
        translation_available: false,
        name: {
            fi: 'venäjä',
        },
        '@id': 'https://api.hel.fi/linkedevents-test/v1/language/ru/',
        '@context': 'http://schema.org',
        '@type': 'Language',
    },
    {
        id: 'et',
        translation_available: false,
        name: {
            fi: 'viro',
        },
        '@id': 'https://api.hel.fi/linkedevents-test/v1/language/et/',
        '@context': 'http://schema.org',
        '@type': 'Language',
    },
    {
        id: 'fr',
        translation_available: false,
        name: {
            fi: 'ranska',
        },
        '@id': 'https://api.hel.fi/linkedevents-test/v1/language/fr/',
        '@context': 'http://schema.org',
        '@type': 'Language',
    },
    {
        id: 'so',
        translation_available: false,
        name: {
            fi: 'somali',
        },
        '@id': 'https://api.hel.fi/linkedevents-test/v1/language/so/',
        '@context': 'http://schema.org',
        '@type': 'Language',
    },
    {
        id: 'es',
        translation_available: false,
        name: {
            fi: 'espanja',
        },
        '@id': 'https://api.hel.fi/linkedevents-test/v1/language/es/',
        '@context': 'http://schema.org',
        '@type': 'Language',
    },
    {
        id: 'tr',
        translation_available: false,
        name: {
            fi: 'turkki',
        },
        '@id': 'https://api.hel.fi/linkedevents-test/v1/language/tr/',
        '@context': 'http://schema.org',
        '@type': 'Language',
    },
    {
        id: 'zh',
        translation_available: false,
        name: {
            fi: 'kiina',
        },
        '@id': 'https://api.hel.fi/linkedevents-test/v1/language/zh/',
        '@context': 'http://schema.org',
        '@type': 'Language',
    },
    {
        id: 'fa',
        translation_available: false,
        name: {
            fi: 'persia',
        },
        '@id': 'https://api.hel.fi/linkedevents-test/v1/language/fa/',
        '@context': 'http://schema.org',
        '@type': 'Language',
    },
    {
        id: 'ar',
        translation_available: false,
        name: {
            fi: 'arabia',
        },
        '@id': 'https://api.hel.fi/linkedevents-test/v1/language/ar/',
        '@context': 'http://schema.org',
        '@type': 'Language',
    },
];

export const mockImages = [
    {
        id: 47696,
        license: 'cc_by',
        created_time: '2018-11-16T15:04:44.720111Z',
        last_modified_time: '2018-11-16T15:04:44.720130Z',
        name: '',
        url: 'https://www.helmet.fi/download/noname/{482BADF8-A86A-4D10-BF30-4FE0DC7A73E7}/69190',
        cropping: '',
        photographer_name: null,
        data_source: 'helmet',
        publisher: 'ahjo:u4804001010',
        '@id': 'https://api.hel.fi/linkedevents-test/v1/image/47696/',
        '@context': 'http://schema.org',
        '@type': 'ImageObject',
    },
    {
        id: 47695,
        license: 'cc_by',
        created_time: '2018-11-16T15:04:43.074981Z',
        last_modified_time: '2018-11-16T15:04:43.075001Z',
        name: '',
        url: 'https://www.helmet.fi/download/noname/{BCA5FC49-8479-458A-8C50-ED041623837B}/69214',
        cropping: '',
        photographer_name: null,
        data_source: 'helmet',
        publisher: 'ahjo:u4804001010',
        '@id': 'https://api.hel.fi/linkedevents-test/v1/image/47695/',
        '@context': 'http://schema.org',
        '@type': 'ImageObject',
    },
    {
        id: 47694,
        license: 'cc_by',
        created_time: '2018-11-16T15:04:42.563744Z',
        last_modified_time: '2018-11-16T15:04:42.563762Z',
        name: '',
        url: 'https://www.helmet.fi/download/noname/{35F0C5D4-BD73-4D4F-B798-1F3D9C530AAE}/69221',
        cropping: '',
        photographer_name: null,
        data_source: 'helmet',
        publisher: 'ahjo:u4804001010',
        '@id': 'https://api.hel.fi/linkedevents-test/v1/image/47694/',
        '@context': 'http://schema.org',
        '@type': 'ImageObject',
    },
    {
        id: 47693,
        license: 'cc_by',
        created_time: '2018-11-16T15:04:41.097735Z',
        last_modified_time: '2018-11-16T15:04:41.097753Z',
        name: '',
        url: 'https://www.helmet.fi/download/noname/{F1E07D11-EA41-4343-AD0E-7413789AF15E}/69199',
        cropping: '',
        photographer_name: null,
        data_source: 'helmet',
        publisher: 'ahjo:u4804001010',
        '@id': 'https://api.hel.fi/linkedevents-test/v1/image/47693/',
        '@context': 'http://schema.org',
        '@type': 'ImageObject',
    },
];

export const dummyUser = {
    id: 'testuser',
    username: 'fooUser',
    provider: 'helsinki',
};

// mock reducers for redux store
export const mockUserEventsReducer = {
    isFetching: false,
    fetchComplete: true,
    items: mockUserEvents,
    error: null,
    sortBy: 'last_modified_time',
    sortOrder: 'desc',
    count: 738,
    paginationPage: 0,
};

export const mockEventsReducer = {
    apiErrorMsg: null,
    isFetching: false,
    fetchComplete: false,
    items: [],
    eventError: null,
    eventsError: null,
};

export const mockAppReducer = {
    flashMsg: null,
    confirmAction: null,
};

export const mockSubEventsReducer = {
    isFetching: false,
    fetchComplete: false,
    items: [],
    error: null,
};

export const mockEditorNewEvent = {
    values: {
        sub_events: {},
    },
    languages: mockLanguages.slice(0, 3),
    contentLanguages: [
        'fi',
    ],
    keywordSets: mockKeywordSets.slice(0, 3),
    validationErrors: {},
    validateFor: null,
};

export const mockEditorExistingEvent = {
    values: {
        id: 'helsinki:afqxukccli',
        name: {
            sv: 'ExampleEventForUnitTests_otsikkosv',
            fi: 'ExampleEventForUnitTests_otsikkofi',
        },
        short_description: {
            sv: 'En kort beskrivning',
            fi: 'Lyhyt suomeksi',
        },
        description: {
            sv: '<p>Kuvaus ruotsiksi</p>',
            fi: '<p>Kuvaus suomeksi</p>',
        },
        info_url: {
            sv: 'http://bar.sv',
            fi: 'http://foo.fi',
        },
        provider: {
            sv: 'Jårkkari',
            fi: 'Järkkäri',
        },
        event_status: 'EventScheduled',
        publication_status: 'public',
        organization: 'ahjo:02100',
        location: {
            id: 'matko:587',
            divisions: [
                {
                    type: 'sub_district',
                    ocd_id: 'ocd-division/country:fi/kunta:helsinki/osa-alue:kruununhaka',
                    municipality: 'Helsinki',
                    name: {
                        sv: 'Kronohagen',
                        fi: 'Kruununhaka',
                    },
                },
                {
                    type: 'district',
                    ocd_id: 'ocd-division/country:fi/kunta:helsinki/peruspiiri:vironniemi',
                    municipality: 'Helsinki',
                    name: {
                        sv: 'Estnäs',
                        fi: 'Vironniemi',
                    },
                },
                {
                    type: 'neighborhood',
                    ocd_id: 'ocd-division/country:fi/kunta:helsinki/kaupunginosa:kruununhaka',
                    municipality: 'Helsinki',
                    name: {
                        sv: 'Kronohagen',
                        fi: 'Kruununhaka',
                    },
                },
                {
                    type: 'muni',
                    ocd_id: 'ocd-division/country:fi/kunta:helsinki',
                    municipality: null,
                    name: {
                        sv: 'Helsingfors',
                        fi: 'Helsinki',
                    },
                },
            ],
            custom_data: null,
            created_time: null,
            last_modified_time: '2017-09-04T14:05:13.317545Z',
            email: null,
            contact_type: null,
            address_region: null,
            postal_code: null,
            post_office_box_num: null,
            address_country: null,
            deleted: false,
            n_events: 0,
            data_source: 'matko',
            image: null,
            publisher: 'ytj:0586977-6',
            parent: null,
            replaced_by: null,
            position: {
                coordinates: [
                    24.9521506,
                    60.1707042,
                ],
                type: 'Point',
            },
            name: {
                en: 'The Cathedral Crypt',
                sv: 'Domkyrkans krypta',
                fi: 'Tuomiokirkon krypta',
            },
            address_locality: null,
            description: {
                en: 'The crypt of the church was originally a cellar where the heating devices and firewood storage were located. The facility with its earth floor was renovated in the 1972-73 in accordance with architect Tarja Salmio-Toiviainen\'s plan. The heart of the crypt is a small chapel. Concerts and exhibitions, and in summer Café Krypta.',
                sv: 'Domkyrkans krypta var ursprungligen Domkyrkans källare där man bl.a. förvarade veden som kyrkan värmdes med. Källaren med jordgolv stod sedan tom i nästan hundra år. Åren 1972-73 renoverades den grundligt enligt arkitekt Tarja Salmio-Toiviainens ritningar efter vilket den togs i bruk i församlingen. Dess hjärta är ett litet kapell. Förutom utrymme för församlingen, ordnas här konserter och utställningar. Sommartid Café Krypta. I Domkyrkans krypta anordnas evenemang och utställningar.',
                fi: 'Tuomiokirkon krypta rakennettiin alun perin kirkon kellariksi, jossa sijaitsivat kirkon lämmityslaitteet ja halkovarastot. Maalattiainen kellari oli tyhjillään yli sata vuotta. Krypta remontoitiin vuosina 1972-73 arkkitehti Tarja Salmio-Toiviaisen suunnitelmien mukaan ja otettiin sen jälkeen toiminnalliseen käyttöön. Sen sydän on pieni kappeli. Krypta toimii seurakunnan hartaus- ja kokoontumispaikkana, ja siellä järjestetään myös konsertteja ja näyttelyitä. Kesäisin kryptassa toimii Café Krypta.',
            },
            street_address: null,
            telephone: null,
            info_url: {
                en: 'http://www.helsinginseurakunnat.fi/seurakunnat/tuomiokirkkoseurakunta/touristinformation.html',
                sv: 'http://www.helsinginseurakunnat.fi/seurakunnat/tuomiokirkkoseurakunta/touristinformation.html',
                fi: 'http://www.helsinginseurakunnat.fi/seurakunnat/tuomiokirkkoseurakunta/yhteystiedot_0/kirkot/tuomiokirkko/tuomiokirkonkrypta.html',
            },
            '@id': 'https://api.hel.fi/linkedevents-test/v1/place/matko:587/',
            '@context': 'http://schema.org',
            '@type': 'Place',
        },
        location_extra_info: {
            sv: 'Det händer på kryptan',
            fi: 'Kryptassa tapahtuu',
        },
        offers: [
            {
                is_free: false,
                price: {
                    sv: '10000 kronor',
                    fi: '110 euroa',
                },
                description: {
                    sv: 'hintaruotsiksi',
                    fi: 'hintasuomeksi',
                },
                info_url: {
                    sv: 'http://kryptatapahtuma.sv',
                    fi: 'http://kryptatapahtuma.fi',
                },
            },
        ],
        sub_events: {},
        keywords: [
            {
                value: 'https://api.hel.fi/linkedevents-test/v1/keyword/yso:p360/',
                label: 'kulttuuritapahtumat',
            },
            {
                value: 'https://api.hel.fi/linkedevents-test/v1/keyword/yso:p1103/',
                label: 'retkeily',
            },
        ],
        audience: [
            'https://api.hel.fi/linkedevents-test/v1/keyword/helfi:2/',
            'https://api.hel.fi/linkedevents-test/v1/keyword/yso:p11617/',
            'https://api.hel.fi/linkedevents-test/v1/keyword/helsinki:aflfbatkwe/',
        ],
        in_language: [
            'https://api.hel.fi/linkedevents-test/v1/language/fi/',
            'https://api.hel.fi/linkedevents-test/v1/language/sv/',
        ],
        extlink_facebook: 'http://kasvokirja.fi',
        extlink_twitter: 'http://twiitti.fi',
        extlink_instagram: 'http://instataan.com',
        start_time: '2038-02-12T13:16:00Z',
        end_time: '2038-02-12T15:18:00Z',
    },
    languages: mockLanguages,
    contentLanguages: [
        'fi',
        'sv',
    ],
    keywordSets: mockKeywordSets,
    validationErrors: {},
    validateFor: null,
    validationStatus: 'resolve',
};

export const mockOrganizations =  [
      {
        "id": "yso:1200",
        "data_source": "yso",
        "classification": "org:13",
        "name": "YSO",
        "founding_date": null,
        "dissolution_date": null,
        "parent_organization": null,
        "sub_organizations": [],
        "affiliated_organizations": [],
        "created_time": "2022-11-15T14:23:56.473676Z",
        "last_modified_time": "2022-11-15T14:23:56.483698Z",
        "is_affiliated": false,
        "replaced_by": null,
        "has_regular_users": false,
        "@id": "http://localhost:8006/v1/organization/yso:1200/",
        "@context": "http://schema.org",
        "@type": "Organization"
      },
      {
        "id": "turku:853",
        "data_source": "turku",
        "classification": "org:3",
        "name": "Turun kaupunki",
        "founding_date": null,
        "dissolution_date": null,
        "parent_organization": null,
        "sub_organizations": [
          "http://localhost:8006/v1/organization/turku:04/",
          "http://localhost:8006/v1/organization/turku:12/",
          "http://localhost:8006/v1/organization/turku:25/",
          "http://localhost:8006/v1/organization/turku:40/",
          "http://localhost:8006/v1/organization/turku:44/",
          "http://localhost:8006/v1/organization/turku:61/",
          "http://localhost:8006/v1/organization/turku:80/"
        ],
        "affiliated_organizations": [],
        "created_time": "2022-11-16T06:34:02.325022Z",
        "last_modified_time": "2022-11-16T06:34:02.325859Z",
        "is_affiliated": false,
        "replaced_by": null,
        "has_regular_users": false,
        "@id": "http://localhost:8006/v1/organization/turku:853/",
        "@context": "http://schema.org",
        "@type": "Organization"
      },
      {
        "id": "turku:04",
        "data_source": "turku",
        "classification": "org:3",
        "name": "Konsernihallinto ja palvelukeskukset",
        "founding_date": null,
        "dissolution_date": null,
        "parent_organization": "http://localhost:8006/v1/organization/turku:853/",
        "sub_organizations": [
          "http://localhost:8006/v1/organization/turku:0719/",
          "http://localhost:8006/v1/organization/turku:0720/"
        ],
        "affiliated_organizations": [],
        "created_time": "2022-11-16T06:34:02.334476Z",
        "last_modified_time": "2022-11-16T06:34:02.336007Z",
        "is_affiliated": false,
        "replaced_by": null,
        "has_regular_users": false,
        "@id": "http://localhost:8006/v1/organization/turku:04/",
        "@context": "http://schema.org",
        "@type": "Organization"
      },
      {
        "id": "turku:0719",
        "data_source": "turku",
        "classification": "org:3",
        "name": "Matkailun palvelukeskus",
        "founding_date": null,
        "dissolution_date": null,
        "parent_organization": "http://localhost:8006/v1/organization/turku:04/",
        "sub_organizations": [],
        "affiliated_organizations": [],
        "created_time": "2022-11-16T06:34:02.356685Z",
        "last_modified_time": "2022-11-16T06:34:02.357700Z",
        "is_affiliated": false,
        "replaced_by": null,
        "has_regular_users": false,
        "@id": "http://localhost:8006/v1/organization/turku:0719/",
        "@context": "http://schema.org",
        "@type": "Organization"
      },
      {
        "id": "turku:0720",
        "data_source": "turku",
        "classification": "org:3",
        "name": "Työllisyyspalvelukeskus",
        "founding_date": null,
        "dissolution_date": null,
        "parent_organization": "http://localhost:8006/v1/organization/turku:04/",
        "sub_organizations": [],
        "affiliated_organizations": [],
        "created_time": "2022-11-16T06:34:02.359649Z",
        "last_modified_time": "2022-11-16T06:34:02.360651Z",
        "is_affiliated": false,
        "replaced_by": null,
        "has_regular_users": false,
        "@id": "http://localhost:8006/v1/organization/turku:0720/",
        "@context": "http://schema.org",
        "@type": "Organization"
      },
      {
        "id": "turku:12",
        "data_source": "turku",
        "classification": "org:3",
        "name": "Varsinais-Suomen aluepelastuslaitos",
        "founding_date": null,
        "dissolution_date": null,
        "parent_organization": "http://localhost:8006/v1/organization/turku:853/",
        "sub_organizations": [],
        "affiliated_organizations": [],
        "created_time": "2022-11-16T06:34:02.338372Z",
        "last_modified_time": "2022-11-16T06:34:02.339406Z",
        "is_affiliated": false,
        "replaced_by": null,
        "has_regular_users": false,
        "@id": "http://localhost:8006/v1/organization/turku:12/",
        "@context": "http://schema.org",
        "@type": "Organization"
      },
      {
        "id": "turku:25",
        "data_source": "turku",
        "classification": "org:3",
        "name": "Hyvinvointitoimiala",
        "founding_date": null,
        "dissolution_date": null,
        "parent_organization": "http://localhost:8006/v1/organization/turku:853/",
        "sub_organizations": [],
        "affiliated_organizations": [],
        "created_time": "2022-11-16T06:34:02.341425Z",
        "last_modified_time": "2022-11-16T06:34:02.342418Z",
        "is_affiliated": false,
        "replaced_by": null,
        "has_regular_users": false,
        "@id": "http://localhost:8006/v1/organization/turku:25/",
        "@context": "http://schema.org",
        "@type": "Organization"
      },
      {
        "id": "turku:40",
        "data_source": "turku",
        "classification": "org:3",
        "name": "Sivistystoimiala",
        "founding_date": null,
        "dissolution_date": null,
        "parent_organization": "http://localhost:8006/v1/organization/turku:853/",
        "sub_organizations": [
          "http://localhost:8006/v1/organization/turku:4032/",
          "http://localhost:8006/v1/organization/turku:4031/"
        ],
        "affiliated_organizations": [],
        "created_time": "2022-11-16T06:34:02.344416Z",
        "last_modified_time": "2022-11-16T06:34:02.345408Z",
        "is_affiliated": false,
        "replaced_by": null,
        "has_regular_users": false,
        "@id": "http://localhost:8006/v1/organization/turku:40/",
        "@context": "http://schema.org",
        "@type": "Organization"
      },
      {
        "id": "turku:4032",
        "data_source": "turku",
        "classification": "org:3",
        "name": "Ammatillinen koulutus",
        "founding_date": null,
        "dissolution_date": null,
        "parent_organization": "http://localhost:8006/v1/organization/turku:40/",
        "sub_organizations": [],
        "affiliated_organizations": [],
        "created_time": "2022-11-16T06:34:02.362620Z",
        "last_modified_time": "2022-11-16T06:34:02.363629Z",
        "is_affiliated": false,
        "replaced_by": null,
        "has_regular_users": false,
        "@id": "http://localhost:8006/v1/organization/turku:4032/",
        "@context": "http://schema.org",
        "@type": "Organization"
      },
      {
        "id": "turku:4031",
        "data_source": "turku",
        "classification": "org:3",
        "name": "Lukiokoulutus",
        "founding_date": null,
        "dissolution_date": null,
        "parent_organization": "http://localhost:8006/v1/organization/turku:40/",
        "sub_organizations": [],
        "affiliated_organizations": [],
        "created_time": "2022-11-16T06:34:02.365676Z",
        "last_modified_time": "2022-11-16T06:34:02.366915Z",
        "is_affiliated": false,
        "replaced_by": null,
        "has_regular_users": false,
        "@id": "http://localhost:8006/v1/organization/turku:4031/",
        "@context": "http://schema.org",
        "@type": "Organization"
      },
      {
        "id": "turku:44",
        "data_source": "turku",
        "classification": "org:3",
        "name": "Vapaa-aikatoimiala",
        "founding_date": null,
        "dissolution_date": null,
        "parent_organization": "http://localhost:8006/v1/organization/turku:853/",
        "sub_organizations": [
          "http://localhost:8006/v1/organization/turku:4453/",
          "http://localhost:8006/v1/organization/turku:4470/",
          "http://localhost:8006/v1/organization/turku:4462/",
          "http://localhost:8006/v1/organization/turku:4480/",
          "http://localhost:8006/v1/organization/turku:4431/"
        ],
        "affiliated_organizations": [],
        "created_time": "2022-11-16T06:34:02.347452Z",
        "last_modified_time": "2022-11-16T06:34:02.348588Z",
        "is_affiliated": false,
        "replaced_by": null,
        "has_regular_users": false,
        "@id": "http://localhost:8006/v1/organization/turku:44/",
        "@context": "http://schema.org",
        "@type": "Organization"
      },
      {
        "id": "turku:4453",
        "data_source": "turku",
        "classification": "org:3",
        "name": "Kirjastopalvelut",
        "founding_date": null,
        "dissolution_date": null,
        "parent_organization": "http://localhost:8006/v1/organization/turku:44/",
        "sub_organizations": [],
        "affiliated_organizations": [],
        "created_time": "2022-11-16T06:34:02.369162Z",
        "last_modified_time": "2022-11-16T06:34:02.370229Z",
        "is_affiliated": false,
        "replaced_by": null,
        "has_regular_users": false,
        "@id": "http://localhost:8006/v1/organization/turku:4453/",
        "@context": "http://schema.org",
        "@type": "Organization"
      },
      {
        "id": "turku:4470",
        "data_source": "turku",
        "classification": "org:3",
        "name": "Liikuntapalvelut",
        "founding_date": null,
        "dissolution_date": null,
        "parent_organization": "http://localhost:8006/v1/organization/turku:44/",
        "sub_organizations": [],
        "affiliated_organizations": [],
        "created_time": "2022-11-16T06:34:02.372275Z",
        "last_modified_time": "2022-11-16T06:34:02.373277Z",
        "is_affiliated": false,
        "replaced_by": null,
        "has_regular_users": false,
        "@id": "http://localhost:8006/v1/organization/turku:4470/",
        "@context": "http://schema.org",
        "@type": "Organization"
      },
      {
        "id": "turku:4462",
        "data_source": "turku",
        "classification": "org:3",
        "name": "Museopalvelut",
        "founding_date": null,
        "dissolution_date": null,
        "parent_organization": "http://localhost:8006/v1/organization/turku:44/",
        "sub_organizations": [],
        "affiliated_organizations": [],
        "created_time": "2022-11-16T06:34:02.375285Z",
        "last_modified_time": "2022-11-16T06:34:02.376281Z",
        "is_affiliated": false,
        "replaced_by": null,
        "has_regular_users": false,
        "@id": "http://localhost:8006/v1/organization/turku:4462/",
        "@context": "http://schema.org",
        "@type": "Organization"
      },
      {
        "id": "turku:4480",
        "data_source": "turku",
        "classification": "org:3",
        "name": "Nuorisopalvelut",
        "founding_date": null,
        "dissolution_date": null,
        "parent_organization": "http://localhost:8006/v1/organization/turku:44/",
        "sub_organizations": [],
        "affiliated_organizations": [],
        "created_time": "2022-11-16T06:34:02.378286Z",
        "last_modified_time": "2022-11-16T06:34:02.379322Z",
        "is_affiliated": false,
        "replaced_by": null,
        "has_regular_users": false,
        "@id": "http://localhost:8006/v1/organization/turku:4480/",
        "@context": "http://schema.org",
        "@type": "Organization"
      },
      {
        "id": "turku:4431",
        "data_source": "turku",
        "classification": "org:3",
        "name": "Turun Kaupunginorkesteri",
        "founding_date": null,
        "dissolution_date": null,
        "parent_organization": "http://localhost:8006/v1/organization/turku:44/",
        "sub_organizations": [],
        "affiliated_organizations": [],
        "created_time": "2022-11-16T06:34:02.381279Z",
        "last_modified_time": "2022-11-16T06:34:02.382411Z",
        "is_affiliated": false,
        "replaced_by": null,
        "has_regular_users": false,
        "@id": "http://localhost:8006/v1/organization/turku:4431/",
        "@context": "http://schema.org",
        "@type": "Organization"
      },
      {
        "id": "turku:61",
        "data_source": "turku",
        "classification": "org:3",
        "name": "Kaupunkiympäristötoimiala",
        "founding_date": null,
        "dissolution_date": null,
        "parent_organization": "http://localhost:8006/v1/organization/turku:853/",
        "sub_organizations": [],
        "affiliated_organizations": [],
        "created_time": "2022-11-16T06:34:02.350704Z",
        "last_modified_time": "2022-11-16T06:34:02.351731Z",
        "is_affiliated": false,
        "replaced_by": null,
        "has_regular_users": false,
        "@id": "http://localhost:8006/v1/organization/turku:61/",
        "@context": "http://schema.org",
        "@type": "Organization"
      },
      {
        "id": "turku:80",
        "data_source": "turku",
        "classification": "org:3",
        "name": "Turun Kaupunginteatteri",
        "founding_date": null,
        "dissolution_date": null,
        "parent_organization": "http://localhost:8006/v1/organization/turku:853/",
        "sub_organizations": [],
        "affiliated_organizations": [],
        "created_time": "2022-11-16T06:34:02.353734Z",
        "last_modified_time": "2022-11-16T06:34:02.354736Z",
        "is_affiliated": false,
        "replaced_by": null,
        "has_regular_users": false,
        "@id": "http://localhost:8006/v1/organization/turku:80/",
        "@context": "http://schema.org",
        "@type": "Organization"
      },
      {
        "id": "yksilo:2000",
        "data_source": "yksilo",
        "classification": "org:11",
        "name": "Yksityishenkilöt",
        "founding_date": null,
        "dissolution_date": null,
        "parent_organization": null,
        "sub_organizations": [],
        "affiliated_organizations": [],
        "created_time": "2022-11-16T06:34:02.328096Z",
        "last_modified_time": "2022-11-16T08:44:16.202926Z",
        "is_affiliated": false,
        "replaced_by": null,
        "has_regular_users": false,
        "@id": "http://localhost:8006/v1/organization/yksilo:2000/",
        "@context": "http://schema.org",
        "@type": "Organization"
      },
      {
        "id": "virtual:3000",
        "data_source": "virtual",
        "classification": "org:14",
        "name": "Virtuaalitapahtumat",
        "founding_date": null,
        "dissolution_date": null,
        "parent_organization": null,
        "sub_organizations": [],
        "affiliated_organizations": [],
        "created_time": "2022-11-16T06:34:02.331109Z",
        "last_modified_time": "2022-11-16T06:34:02.331796Z",
        "is_affiliated": false,
        "replaced_by": null,
        "has_regular_users": false,
        "@id": "http://localhost:8006/v1/organization/virtual:3000/",
        "@context": "http://schema.org",
        "@type": "Organization"
      }
    ];

export const mockOrgClassifications = [
    {
      "id": "org:1",
      "name": "Valtiollinen toimija",
      "@id": "org:1",
      "@context": "http://schema.org",
      "@type": "OrganizationClass"
    },
    {
      "id": "org:10",
      "name": "Muu yhteisö",
      "@id": "org:10",
      "@context": "http://schema.org",
      "@type": "OrganizationClass"
    },
    {
      "id": "org:11",
      "name": "Yksityishenkilö",
      "@id": "org:11",
      "@context": "http://schema.org",
      "@type": "OrganizationClass"
    },
    {
      "id": "org:2",
      "name": "Maakunnallinen toimija",
      "@id": "org:2",
      "@context": "http://schema.org",
      "@type": "OrganizationClass"
    },
    {
      "id": "org:3",
      "name": "Kunta",
      "@id": "org:3",
      "@context": "http://schema.org",
      "@type": "OrganizationClass"
    },
    {
      "id": "org:4",
      "name": "Kunnan liikelaitos",
      "@id": "org:4",
      "@context": "http://schema.org",
      "@type": "OrganizationClass"
    },
    {
      "id": "org:5",
      "name": "Valtion liikelaitos",
      "@id": "org:5",
      "@context": "http://schema.org",
      "@type": "OrganizationClass"
    },
    {
      "id": "org:6",
      "name": "Yritys",
      "@id": "org:6",
      "@context": "http://schema.org",
      "@type": "OrganizationClass"
    },
    {
      "id": "org:7",
      "name": "Säätiö",
      "@id": "org:7",
      "@context": "http://schema.org",
      "@type": "OrganizationClass"
    },
    {
      "id": "org:8",
      "name": "Seurakunta",
      "@id": "org:8",
      "@context": "http://schema.org",
      "@type": "OrganizationClass"
    },
    {
      "id": "org:9",
      "name": "Yhdistys tai seura",
      "@id": "org:9",
      "@context": "http://schema.org",
      "@type": "OrganizationClass"
    }
  ]

export const mockLocalities = [
    {
        "fi": "Turku",
        "sv": "Åbo",
        "en": null
    },
    {
        "fi": "Naantali",
        "sv": "Nådendal",
        "en": "Naantali"
    }
]
